Event ordering information is a must for data change events
zalando/restful-api-guidelines pull request #644
Opened 2021-03-09 12:50 UTC by tfrauenstein

https://github.com/zalando/restful-api-guidelines/issues/629

2021-03-09 14:17 UTC, ePaul commented on chapters/events.adoc
> +== {MUST} provide explicit event ordering for data change events
From the discussion in the meeting, this might be a better way to structure it into two rules, to capture SHOULD + MUST:

* {SHOULD} provide explicit event ordering (for general events)
** general reasoning why it's needed
* {MUST} provide explicit event ordering for data change events
** reasoning why it's even more needed for data change events

2021-03-12 15:24 UTC, tkrop requested changes
Sorry, that the review took so long. Please have a look at my comments.

2021-03-12 15:24 UTC, tkrop commented on chapters/events.adoc
> +== {MUST} provide explicit event ordering for data change events
For my opinion, this all is getting way to long and complicated for users to follow and understand. The section is mixing up the fundamental discussions about event ordering and the practical approach how to implement this in Zalando with very specific details of data analytics and their motivation in Zalando. More over it is turning this logical order around making it in my opinion hard to follow.

As mentioned in the meeting, I would stick to the before order of present the general motivation and discussion about event ordering in the general *should* rule. This than should be followed by the spacial data change event motivation and discussion of the impact for data analytics in the *must* rule to keep both parts understandable. Here is my suggestion using your work how this may be formulated:

```
[203]
== {SHOULD} provide explicit event ordering (for general events)

Some uses case, e.g. processing errors, require event consumers to reconstruct
an event streams or replay events outside the context of the original event
stream. To support this, events _should_ contain a way to restore the partial
order of related events.

This can be done – among other ways – by adding

 * a strictly monotonically increasing version (e.g. as created by a database)
   to an entity, or
 * a strictly monotonically increasing event counter (per partition or entity).

*Hint:* timestamps are often a bad choice, since synchronization of clocks
in distributed systems is difficult and system clocks may jump forward and
backward to compensate drifts or leap-seconds. When despite using timestamps to
indicate event ordering, you *must* carefully ensure that the designated event
order is not messed up by these effects and use UTC time zone format.

To accomplish this explicit event ordering the event type definition

* *must* specify a the `ordering_key_fields` property to indicate which
  field(s) contain the ordering key, and
* *should* specify the `ordering_instance_ids` property to define which
  field(s) represents the data instance identifier.

*Note:* The `ordering_instance_ids` can be used to restrict the scope in which
the `ordering_key_fields` provide the strict order. If undefined, the ordering
is assumed to be provided in scope of all events.

*Remark:* event odering based on data structures that can be converged upon
in a distributed system, e.g. https://en.wikipedia.org/wiki/Logical_clock[logical
clocks] or https://en.wikipedia.org/wiki/Vector_clock[vector clocks]), are
outside the scope of this guidance.

[242]
== {MUST} provide explicit event ordering for data change events

All data change events *must* provided explicit event ordering by defining the
`ordering_key_fields` and `ordering_instance_ids` as proposed in <<203>>. This
is required to enable the change data capturing of our analytics platform to
reconstruct the event order after failures, and keep the replicated data store
in sync with the source.

*Note:* The `occured_at` and `partition_offset` metadata of Nakadi provide no
event ordering, since Nakadi is a distributed concurrent system without atomic,
ordered event publication. The ordering information is business knowledge
provided by the event publisher. It is typically implemented in scope of event
partitions or specific entities, but may also comply all events, if scaling
requirements are low.
```

I must admit, the last paragraph could as well be located in the general rule.

2021-03-13 16:55 UTC, tfrauenstein commented on chapters/events.adoc
> +entities, and used for data replication based data integration.
👍

2021-03-13 16:58 UTC, tfrauenstein commented on chapters/events.adoc
> +transactional datasets as input for data analytics and AI.
👍

2021-03-13 17:07 UTC, tfrauenstein commented on chapters/events.adoc
> +concurrent system without ordered atomic event publication.
'Transactional data' is a common term used in data analytics, to differentiate from 'analytics data'. 
I'm not talking here about 'transactions' or 'atomic' operations. 
However, I will change the wording to void misunderstandings:
a) The ordering information defines the change order of the transactional data managed
by the application, and ...
b) since application's event creation may not reflect the order of the transactional data changes and Nakadi...

2021-03-13 17:13 UTC, tfrauenstein commented on chapters/events.adoc
> +== {MUST} provide explicit event ordering for data change events
I'm not convinced, but it also makes sense -- will do it.

2021-03-15 08:02 UTC, tkrop commented on chapters/events.adoc
> +of event publishing may not exactly reflect the business order. The business ordering
1. I would like to prevent `(i)` and `(ii)` here for style reasons and use (1), (2).
2. `occured_at` -> `occurred_at` (my fault).
3. (ii) has no conjunction to `occurred_at` and `partition_offset` because these are set on the Nakadi service side.

Besides, I'm not sure whether (ii) is of much help for the reader: Programmers will argue that they can and will take care of this (using the database transactions handling). The danger here is more, that they are often not aware when their Nakadi libraries on low concurrency levels not ensuring the business order for the sake of speed, but this is just based on guessing, since we can't know the details.

2021-03-15 08:16 UTC, tkrop commented on chapters/events.adoc
> +transactional datasets used as input for data analytics and AI.
Please circumvent the use of `transactional dataset` here, since (1) the type of data is of no relevance for this rule, and (2) term `transactional` can be easily interpreted out of context here. While `transactional datasets` in data mining refer to the *business transactions* captured by a data set, the connotation in data change events and event ordering can be to easily misunderstood as *database transactions*.

2021-03-15 08:24 UTC, tkrop commented on chapters/events.adoc
> +All general events (fka business events) *should* be provided with the explicit
Why do you want to remove the brackets around `for general events`?

I think this restricts the rule more than necessary, since it suggests that none-general events are not included, which should not be our intention. This is especially supported by defining general events as equivalent to business events `(fka business events)`. In this context here I would keep `(for general events)` in the title and stick to `All events *should* ...` to make it as general as possible.

2021-03-15 08:29 UTC, tkrop commented on chapters/events.adoc
> +== {SHOULD} provide explicit event ordering for general events
Please correct rule numbering and rule order as follows:

```
[#202]
== {MUST} use data change events to signal mutations
...

[#203]
== {SHOULD} provide explicit event ordering (for general events)
...

[#242]
== {MUST} provide explicit event ordering for data change events
...
```

2021-03-15 08:30 UTC, tkrop commented
@tfrauenstein I think we are getting to a very good compromise.

2021-03-15 09:03 UTC, tfrauenstein commented on chapters/events.adoc
> +of event publishing may not exactly reflect the business order. The business ordering
1+2) +1
3) I think the conjunction is given -- the statement is that it does not reflect the business order (not that it is set by Nakadi)
4) understood, but IMO the hint is helpful -- the Nakadi concurrency problem is not the only problem to solve to provide the business order.

2021-03-15 09:50 UTC, tfrauenstein commented on chapters/events.adoc
> +transactional datasets used as input for data analytics and AI.
In data analytics, 'transactional dataset' we use the term intensively  for 'datasets sourced from OLTP productive environment'  -- we should explicitly refer to this term. However, changed the wording a bit.

2021-03-15 09:55 UTC, tfrauenstein commented on chapters/events.adoc
> +All general events (fka business events) *should* be provided with the explicit
'All events *should*...' is not correct, since it is a must for data change events.
We have two event categories: general vs. data change -- and a want to avoid misunderstanding wrt 'should' vs. 'must'.

2021-03-15 10:01 UTC, tfrauenstein commented on chapters/events.adoc
> +== {SHOULD} provide explicit event ordering for general events
+1

2021-03-15 10:18 UTC, tkrop commented on chapters/events.adoc
> +the guidelines. Implementation experience has shown that the
Just saw this scrolling. Can we write `*Note:* ...` here for consistency?

Besides, I'm wondering about the sentence above with `:` on the end of the sentence. Either `:` is wrong, or the whole sentence is out of context - may be it can be removed at all. Have a look at the example, it contains no `a` or `b` fields.

2021-03-15 10:20 UTC, tkrop commented on chapters/events.adoc
>  field:
Same as in the before comment. The example is likely the one now above, but there is no `a` and `b` fields at all, so may be we can remove it.

2021-03-15 10:23 UTC, tkrop commented on chapters/events.adoc
> +All general events (fka business events) *should* be provided with the explicit
Yes, but making a sentence stronger for a special case in a second sentence is usually no perception problem, while excluding some we want to include may be. But I let this go.

2021-03-15 10:29 UTC, tkrop commented on chapters/events.adoc
> +== {SHOULD} provide explicit event ordering for general events
I would keep rules in order #202, #203, #242, since #203 and #242 have a stronger on each other building context of ordering than #202 and #242 with talking about data change events.

2021-03-15 10:29 UTC, tkrop approved these changes

2021-03-15 10:30 UTC, tkrop commented
:+1:

2021-03-15 10:39 UTC, tfrauenstein commented on chapters/events.adoc
> +the guidelines. Implementation experience has shown that the
+1

2021-03-15 10:41 UTC, tkrop commented on chapters/events.adoc
> +of event publishing may not exactly reflect the business order. The business ordering
Yes, it is definitely hard to solve, but you can't prevent engineers from trying this by challenging them. Might have the opposite effect...

2021-03-15 10:44 UTC, tkrop commented on chapters/events.adoc
> +transactional datasets used as input for data analytics and AI.
My problem is the context of the word not the meaning. I acknowledge that it is known in the data-mining community - however still only 20.000 hits, which is not much. The problem is, that the term is likely to be misunderstood by 80% of the readers.

2021-03-15 10:50 UTC, tkrop commented
:+1:

2021-03-15 10:53 UTC, tfrauenstein commented on chapters/events.adoc
>  field:
+1

2021-03-15 10:53 UTC, tfrauenstein commented on chapters/events.adoc
> +== {SHOULD} provide explicit event ordering for general events
I prefer grouping as of now: grouping by 'category aspect', instead of by 'ordering aspect'

2021-03-15 10:53 UTC, tfrauenstein commented on chapters/events.adoc
> +All general events (fka business events) *should* be provided with the explicit
yes please :-)

2021-03-15 11:06 UTC, vadeg commented
👍

2021-03-15 11:06 UTC, merged