MUST use standard data formats
zalando/restful-api-guidelines pull request #650
Opened 2021-04-06 15:22 UTC by tfrauenstein

https://github.com/zalando/restful-api-guidelines/issues/642

2021-04-12 10:05 UTC, tkrop requested changes
I'm not sure from the perspective of comprehensibility and focus whether it is advisable to collect so many rules into one. May be we can split the rule into *technical* and *business* data formats to make the rules more digestible.

2021-04-12 10:11 UTC, tkrop commented
Seems as if eventually only rule #171 is implemented in Zally. We should change the reference number here, however, keeping the old rule id on the new rule should take care that this will have no negative side effect. Anyhow, it would be great to check whether we can test even more formats based on the new rule definition.

2021-04-12 19:43 UTC, tfrauenstein commented on chapters/data-formats.adoc
> +| `integer` | `int64` | 8 byte signed integer -- see https://en.wikipedia.org/wiki/Integer_(computer_science)[Wiki:Integer]  | `772107100456824`
👍

2021-04-12 19:45 UTC, tfrauenstein commented on chapters/data-formats.adoc
> +| `integer` | `bigint` | >8 byte signed integer range -- see e.g. https://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html[Java Doc] | `77210710045682438959`
It is about value ranges (which i will add) - which at the end is about bytes needed to represent it.

2021-04-12 19:48 UTC, tfrauenstein commented on chapters/data-formats.adoc
> +| `number` | `decimal` | >`binary64` double precision decimal number | `3.141592653589793238462643383279`
👍

2021-04-12 19:55 UTC, tfrauenstein commented on chapters/data-formats.adoc
> +[#238]
I don't see #239 providing more information than its subsumption under #238. 
However, I will check to have some rules as explicit 'duplicates' to highlight its importance and for more context info.

2021-04-13 14:04 UTC, tkrop commented on chapters/data-formats.adoc
> +| `integer` | `bigint` | >8 byte signed integer range -- see e.g. https://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html[Java Doc] | `77210710045682438959`
The number of bytes needed to represent an *arbitrary* large integer is absolute unknown, implementation dependent, and of no relevance. This is why I'm so adamant on this point. The number of bytes needed to represent an `int32` and `int64` is somehow similar of no relevance - in my opinion Open API did a bad choice defining the names giving a bit length. As you say yourself, the range is important, and that is why I favor the before table definition here:

```
|integer |int32 |integer between pass:[-2<sup>31</sup>] and pass:[2<sup>31</sup>]-1
|integer |int64 |integer between pass:[-2<sup>63</sup>] and pass:[2<sup>63</sup>]-1
|integer |bigint |arbitrarily large signed integer number
|number |float |{IEEE-754-2008}[IEEE 754-2008/ISO 60559:2011] binary32 decimal number
|number |double |{IEEE-754-2008}[IEEE 754-2008/ISO 60559:2011] binary64 decimal number
|number |decimal |arbitrarily precise signed decimal number
```

We may even improve on this by defining the significant and exponent range for `double` and `float` instead of repeating the error to reference storage size.

2021-04-13 14:09 UTC, tkrop commented on chapters/data-formats.adoc
> +[#238]
I can't find a subsumption of #239. Can you point me to it?

The important information I see is:

* Exposing binary data using an alternative media type is generally preferred.
* If an alternative content representation is not desired then binary data should
be embedded into the JSON document as a `base64url` (see #239).

I would like to keep this two aspects explicitly stated to stop API designers from being creative in other ways.

2021-06-15 11:33 UTC, tfrauenstein commented
substituted by https://github.com/zalando/restful-api-guidelines/pull/671

2021-06-15 11:34 UTC, tfrauenstein commented
replaced by https://github.com/zalando/restful-api-guidelines/pull/671

2021-06-15 11:34 UTC, closed without merging

2021-06-15 11:34 UTC, tfrauenstein commented on chapters/data-formats.adoc
> +[#238]
done in new PR https://github.com/zalando/restful-api-guidelines/pull/671

2021-06-15 11:35 UTC, tfrauenstein commented on chapters/data-formats.adoc
> +| `integer` | `bigint` | >8 byte signed integer range -- see e.g. https://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html[Java Doc] | `77210710045682438959`
done in new PR https://github.com/zalando/restful-api-guidelines/pull/671